[package]
name = "mqtt-frame"
version = "0.1.1"
edition = "2021"
description = "A lightweight, Sans-I/O MQTT v3.1.1 and v5.0 protocol codec and parser for Danube."
keywords = ["mqtt", "codec", "tokio-util", "parser", "iot"]
authors = ["Dan Rusei <dan.rusei@gmail.com>"]
repository = "https://github.com/danube-messaging/danube"
documentation = "https://docs.rs/mqtt-frame"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
bytes = { version = "1.11" }
tokio-util = { version = "0.7", features = ["codec"] }
thiserror = "2.0"
tracing = "0.1.44"

# Optional: if we want to serialize packets for logging/debugging
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde-support = ["serde"]

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time"] }
rumqttc = "0.24"
futures = "0.3"
